routes/web.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

//group route with prefix "admin"
Route::prefix('admin')->group(function () {
    //group route with middleware "auth"
    Route::group(['middleware' => 'auth'], function() {

        //admin only
        Route::group(['as' => 'admin.'], function() {
            Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
            Route::resource('/category', CategoryController::class);
            Route::resource('/campaign', CampaignController::class);
            //route donatur
            Route::get('/donatur', [DonaturController::class, 'index'])->name('donatur.index');
            //route donation
            Route::get('/donation', [DonationController::class, 'index'])->name('donation.index');
            Route::get('/donation/filter', [DonationController::class, 'filter'])->name('donation.filter');
            //route profile
            Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
            //route resource slider
            Route::resource('/slider', SliderController::class, ['except' => ['show', 'create', 'edit', 'update']]);
        });
    });
});

app/Models/Donation.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;

class Donation extends Model
{
    use HasFactory;

    protected $fillable = [
        'invoice', 'campaign_id', 'donatur_id', 'amount', 'pray', 'status', 'snap_token'
    ];

    /**
     * Get the campaign that owns the Donation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function campaign()
    {
        return $this->belongsTo(Campaign::class);
    }

    /**
     * Get the donatur that owns the Donation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function donatur()
    {
        return $this->belongsTo(Donatur::class);
    }

    /**
     * createdAt
     *
     * @return Attribute
     */
    protected function createdAt(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => Carbon::parse($value)->format('d-M-Y'),
        );
    }

    /**
     * updatedAt
     *
     * @return Attribute
     */
    protected function updatedAt(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => Carbon::parse($value)->format('d-M-Y'),
        );
    }
}

app/Http/Controllers/Admin/DonationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Donation;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DonationController extends Controller
{
    /**
     * index
     *
     * @return void
     */
    public function index()
    {
        return view('admin.donation.index');
    }

    /**
     * filter
     *
     * @param  mixed $request
     * @return void
     */
    public function filter(Request $request)
    {
        $this->validate($request, [
            'date_from'  => 'required',
            'date_to'    => 'required',
        ]);

        $date_from  = $request->date_from;
        $date_to    = $request->date_to;

        //get data donation by range date
        $donations = Donation::where('status', 'success')->whereDate('created_at', '>=', $request->date_from)->whereDate('created_at', '<=', $request->date_to)->get();

        //get total donation by range date
        $total = Donation::where('status', 'success')->whereDate('created_at', '>=', $request->date_from)->whereDate('created_at', '<=', $request->date_to)->sum('amount');

        return view('admin.donation.index', compact('donations', 'total'));
    }
}

resources/views/admin/donation/index.blade.php
@extends('layouts.app', ['title' => 'Donation - Admin'])

@section('content')
<main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-300">
    <div class="container mx-auto px-6 py-8">

        <form action="{{ route('admin.donation.filter') }}" method="GET">
            <div class="flex gap-6">

                <div class="flex-auto">
                    <label class="text-gray-700" for="name">TANGGAL AWAL</label>
                    <input class="form-input w-full mt-2 rounded-md bg-white p-3 shadow-md" type="date" name="date_from"
                        value="{{ old('date_form') ?? request()->query('date_from') }}">
                    @error('date_from')
                        <div class="w-full bg-red-200 shadow-sm rounded-md overflow-hidden mt-2">
                            <div class="px-4 py-2">
                                <p class="text-gray-600 text-sm">{{ $message }}</p>
                            </div>
                        </div>
                    @enderror
                </div>

                <div class="flex-auto">
                    <label class="text-gray-700" for="name">TANGGAL AKHIR</label>
                    <input class="form-input w-full mt-2 rounded-md bg-white p-3 shadow-md" type="date" name="date_to"
                        value="{{ old('date_to') ?? request()->query('date_to') }}">
                    @error('date_to')
                        <div class="w-full bg-red-200 shadow-sm rounded-md overflow-hidden mt-2">
                            <div class="px-4 py-2">
                                <p class="text-gray-600 text-sm">{{ $message }}</p>
                            </div>
                        </div>
                    @enderror
                </div>

                <div class="flex-1">
                    <button type="submit"
                        class="mt-8 w-full p-3 bg-gray-600 text-gray-200 rounded-md shadow-md hover:bg-gray-700 focus:outline-none focus:bg-gray-700">FILTER</button>
                </div>

            </div>
        </form>


        @if($donations ?? '')

            @if(count($donations) > 0)

                <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                    <div class="inline-block min-w-full shadow-sm rounded-lg overflow-hidden">
                        <table class="min-w-full table-auto">
                            <thead class="justify-between">
                                <tr class="bg-gray-600 w-full">
                                    <th class="px-16 py-2">
                                        <span class="text-white">NAMA DONATUR</span>
                                    </th>
                                    <th class="px-16 py-2 text-left">
                                        <span class="text-white">CAMPAIGN</span>
                                    </th>
                                    <th class="px-16 py-2 text-left">
                                        <span class="text-white">TANGGAL</span>
                                    </th>
                                    <th class="px-16 py-2 text-center">
                                        <span class="text-white">JUMLAH DONASI</span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-gray-200">
                                @forelse($donations as $donation)
                                    <tr class="border bg-white">

                                        <td class="px-16 py-2 flex justify-center">
                                            {{ $donation->donatur->name }}
                                        </td>
                                        <td class="px-16 py-2">
                                            {{ $donation->campaign->title }}
                                        </td>
                                        <td class="px-16 py-2">
                                            {{ $donation->created_at }}
                                        </td>
                                        <td class="px-5 py-2 text-right">
                                            {{ moneyFormat($donation->amount) }}
                                        </td>
                                    </tr>
                                @empty
                                    <div class="bg-red-500 text-white text-center p-3 rounded-sm shadow-md">
                                        Data Belum Tersedia!
                                    </div>
                                @endforelse
                                <tr class="border bg-gray-600 text-white font-bold">
                                    <td colspan="3" class="px-5 py-2 justify-center">
                                        TOTAL DONASI
                                    </td>
                                    <td colspan="3" class="px-5 py-2 text-right">
                                        {{ moneyFormat($total) }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            @endif

        @endif

    </div>

</main>
@endsection